//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetail
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public long telephone_no { get; set; }
        public short age { get; set; }
        public string address { get; set; }
    }
}
